package definition

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"

	"formal-gates/internal/engine/compiler"
	"formal-gates/internal/engine/encoder"
)

// 同源生成的两个交付物（相对仓库根；生成物 checked-in，CI 校验零 diff）。
const (
	artifactPath   = "definitions/workflow.json"
	identityPath   = "internal/engine/definition/identity_gen.go"
	generatedByDoc = "// Code generated by gen-definition; DO NOT EDIT."
	regenerateDoc  = "// Regenerate with: go run ./cmd/gen-definition (from the repository root)."
)

// Generate 从包内 authoring 定义表编译→编码→计算 digest，一次动作写出两个
// 同源交付物（ADR-001 决策 4/6，禁止人工双写）：
//
//	<root>/definitions/workflow.json                        canonical 制品
//	<root>/internal/engine/definition/identity_gen.go       期望身份常量 Go 源
//
// 文档化调用方式：在仓库根目录执行 `go run ./cmd/gen-definition`；CI freshness
// 由 internal/engine/definition 的零 diff 测试执行（Generate 到临时目录后与
// checked-in 文件逐字节比对），不可用 round-trip 替代。
func Generate(root string) error {
	cd, err := compiler.Compile(Workflow(), Registry())
	if err != nil {
		return fmt.Errorf("gen-definition: %w", err)
	}
	data, err := encoder.Encode(cd)
	if err != nil {
		return fmt.Errorf("gen-definition: %w", err)
	}
	if err := writeGenerated(filepath.Join(root, filepath.FromSlash(artifactPath)), data); err != nil {
		return err
	}
	src, err := identitySource(string(cd.Version), encoder.Digest(data))
	if err != nil {
		return err
	}
	return writeGenerated(filepath.Join(root, filepath.FromSlash(identityPath)), src)
}

// identitySource 渲染身份常量 Go 源。版本与 digest 都从本生成动作的制品
// 字节派生——期望身份与制品天然同源，人工复制 digest 被结构性排除。
func identitySource(version, digest string) ([]byte, error) {
	src := fmt.Sprintf(`%s
%s

package definition

// 本文件与 definitions/workflow.json 由同一生成动作产出（Generate），禁止
// 人工编辑。期望身份常量供 loader/校验方钉死当前 definition 身份。
//
// 衔接：WorkflowDefinitionDigest 是 internal/validate/phase0.go 手工常量
// CurrentWorkflowDefinitionDigest 的同源替代；phase0 常量按阶段 0 契约保持
// 不动，读取方在后续批次切换到本常量后移除旧值。

const (
	// WorkflowDefinitionVersion 是 canonical 制品的 definition 版本信封。
	WorkflowDefinitionVersion = %q
	// WorkflowDefinitionDigest 是 canonical 制品字节的 SHA-256 摘要
	// （sha256: 前缀，与仓库现行格式一致）。
	WorkflowDefinitionDigest = %q
)
`, generatedByDoc, regenerateDoc, version, digest)
	formatted, err := format.Source([]byte(src))
	if err != nil {
		return nil, fmt.Errorf("gen-definition: format identity source: %w", err)
	}
	return formatted, nil
}

// writeGenerated 以仓库常规权限写出交付物（制品与 Go 源均 0644）。
func writeGenerated(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("gen-definition: %w", err)
	}
	if err := os.WriteFile(path, data, 0o644); err != nil {
		return fmt.Errorf("gen-definition: %w", err)
	}
	return nil
}
